### ISSUE TITLE
Support for Node.js v0.12

### ISSUE THREAD

**Issue by rikkotec** [mmod/nodamysql#12]
When I last updated mysql, I had added macros to accomodate API changes, but hadn't quite added in the support for v0.11 (for working on support for v0.12 before it was released)

Now v0.12 of Node.js is available and its time to get up to speed.  Proper macro updates/definitions will be needed for v0.12 throughout the add-on's source.

Reference to breaking changes and suggested fixes:

http://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/

Yet at the same time I'm thinking about creating a new version specific to v0.12....such as a 2.x.x release (where 0.x would signify v0.10 of node.js) This would alleviate the excessive macros in the current add-on, though we'd likely end up macro'ing for future changes regardless...

Input is welcome!

**Comment by rikkotec** [comment]
Ok, so preparations were made to split the package and accommodate contributions.

The 0.2.x branch is for <= Node.js v0.10.x

The development branch is for >= Node.js v0.12.x

Master will always be the latest stable version (which at this time is v0.2.1 for Node.js v0.10.x)

**Comment by rikkotec** [comment]
Looking through the code, seems the whole issue that was bringing up this error:

In file included from ../nodamysql.cpp:12:0:
../driver.h:132:40: error: expected class-name before ‘{’ token
 class Driver : public node::ObjectWrap {

Was due to a missing header file required in v0.11.13+ of Node.js:

#include <node_object_wrap.h>

Which moved the respective definitions from node.h to node_object_wrap.h.

Adding the correct include for the appropriate version of node, shows progression.  Will update once I've worked through the newly displayed errors as a result of making the above modifications.

**Comment by rikkotec** [comment]
We made some very good progress today - and are hoping to be able to have it working with Node.js v0.12.x by EOD tomorrow -> though don't hold us to that time-frame :P

In the end it looks like we won't have to keep the packages separated (at least for now), as we were able to discern Compiler Macro modifications that will work with the current version of the node API.

However, when they phase out `v8::Isolate::GetCurrent()` we'll likely be forced to separate the packages again.

I'm gonna spend some time cleaning up the macros since I'm going to have to go through all of the source to make the updates anyhow. With any luck perhaps I'll implement them in a way that allows us to macro passing the `isolate` member around in the proper manner so that we may seamlessly support the API changes when they come.

**Comment by rikkotec** [comment]
I've finally gotten some more time to put into providing an update for supporting the breaking API changes in Node.js v0.12.

Originally I planned to split v0.10 and v0.12 into two separate branches, though it doesn't look like I'm going to have to. I was also able to find a nifty way to organize the macros so that after a tad bit of digging you can make sense of the code.

Once I have everything working with v0.10 and v0.12 from the singular source, I'll push and give everyone a chance to dig in that wishes to do so.

**Comment by rikkotec** [comment]
And it's about ready :)

- It builds on v0.12 -> it also passes the tests aside from one or two; which means it's most likely going to be tomorrow that we're supporting v0.12.
- There will remain a branch for 0.10 until the macro implementation works for both versions (which may extend beyond tomorrow.)

**Comment by rikkotec** [comment]
Resolved with commit: #27
